Allowing async functions in proxy
MarkusJx/node-java-bridge pull request #68
Opened 2023-03-27 08:04 UTC by sla100

Hello Markus.
I've been testing your amazing project for a few days now. While using the proxy, I encountered the problem of having to implement the proxy with synchronous methods.

I tested locally in my async function support solution and it seems to work fine. Please see if this could be added to the project.
Regards.

2023-03-27 11:08 UTC, MarkusJx requested changes

2023-03-27 14:50 UTC, MarkusJx approved these changes

2023-03-27 16:43 UTC, sla100 commented
Thank you. I will be waiting for the next release.

2023-03-27 17:44 UTC, MarkusJx commented
But now the changes you've made won't be in the next release as you've closed this MR before it has been merged. I'm confused.

2023-03-28 05:50 UTC, sla100 commented
> But now the changes you've made won't be in the next release as you've closed this MR before it has been merged. I'm confused.

My bad. Sorry!

2023-03-28 07:03 UTC, MarkusJx approved these changes

2023-03-28 09:16 UTC, merged